mv ./database/.gitignore  ./database/sgitignore
mv ./bootstrap/cache/.gitignore  ./bootstrap/cache/sgitignore
mv ./storage/app/public/.gitignore  ./storage/app/public/sgitignore
mv ./storage/app/.gitignore  ./storage/app/sgitignore
mv ./storage/framework/cache/.gitignore  ./storage/framework/cache/sgitignore
mv ./storage/framework/cache/data/.gitignore  ./storage/framework/cache/data/sgitignore
mv ./storage/framework/testing/.gitignore  ./storage/framework/testing/sgitignore
mv ./storage/framework/sessions/.gitignore  ./storage/framework/sessions/sgitignore
mv ./storage/framework/.gitignore  ./storage/framework/sgitignore
mv ./storage/framework/views/.gitignore  ./storage/framework/views/sgitignore
mv ./storage/logs/.gitignore  ./storage/logs/sgitignore
mv ./.gitignore  ./sgitignore
mv ./vendor/hamcrest/hamcrest-php/.gitignore  ./vendor/hamcrest/hamcrest-php/sgitignore
mv ./vendor/facade/ignition/resources/.gitignore  ./vendor/facade/ignition/resources/sgitignore
mv ./vendor/swiftmailer/swiftmailer/.gitignore  ./vendor/swiftmailer/swiftmailer/sgitignore
mv ./vendor/psr/event-dispatcher/.gitignore  ./vendor/psr/event-dispatcher/sgitignore
mv ./vendor/psr/container/.gitignore  ./vendor/psr/container/sgitignore
mv ./vendor/psr/http-factory/.gitignore  ./vendor/psr/http-factory/sgitignore
mv ./vendor/symfony/translation-contracts/.gitignore  ./vendor/symfony/translation-contracts/sgitignore
mv ./vendor/symfony/event-dispatcher-contracts/.gitignore  ./vendor/symfony/event-dispatcher-contracts/sgitignore
mv ./vendor/symfony/deprecation-contracts/.gitignore  ./vendor/symfony/deprecation-contracts/sgitignore
mv ./vendor/symfony/service-contracts/.gitignore  ./vendor/symfony/service-contracts/sgitignore
mv ./vendor/symfony/http-client-contracts/.gitignore  ./vendor/symfony/http-client-contracts/sgitignore
mv ./vendor/sebastian/version/.gitignore  ./vendor/sebastian/version/sgitignore
mv ./vendor/sebastian/resource-operations/.gitignore  ./vendor/sebastian/resource-operations/sgitignore
