# This is a basic workflow to help you get started with Actions

name: teachers.hk-Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 prod:
  runs-on: ubuntu-latest
  environment: prod
  steps:
  - name: 🚚 Get latest code
    uses: actions/checkout@v2
    
  - name: CodeDeploy
    uses: SamKirkland/FTP-Deploy-Action@4.1.0
    with:
      server: ${{ secrets.FTP_HOST }}
      username: ${{ secrets.FTP_USER }}
      password: ${{ secrets.FTP_PASSWORD }}
      log-level: verbose
